### PR TITLE
Add JDK8 to travis test environments

### PR DESCRIPTION
**Pull request by daveyarwood**
To investigate #369.

### CODE REVIEW

**Comment by daveyarwood** [comment]
```
$ jdk_switcher use openjdk8
Sorry, but JDK 'openjdk8' is not known.

The command "jdk_switcher use openjdk8" failed and exited with 1 during .

Your build has been stopped.
```

D'oh!

**Comment by daveyarwood** [comment]
https://docs.travis-ci.com/user/languages/java/#Testing-Against-Multiple-JDKs

> Travis CI provides OpenJDK 6, OpenJDK 7, Oracle JDK 7, and Oracle JDK 8.

OK, so let's try oraclejdk8.

**Comment by daveyarwood** [comment]
Build failed: https://travis-ci.org/zeromq/jeromq/jobs/166533704

```
Results :

Failed tests:   testStateASync(org.zeromq.TestZProxy): Stop sync status is not good! expected:<[STAR]TED> but was:<[EXI]TED>

Tests run: 88, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by daveyarwood** [comment]
@c-rack Shouldn't we fix the build?

**Comment by c-rack** [comment]
Sure! Your PR was about investigating the problem, so I merged it; another PR can fix the build.

**Comment by daveyarwood** [comment]
OK, makes sense.

I looked at the code just briefly to try and figure out why that test is failing, but I'm not able to spend too much time on it at the moment.

Is it possible there is a race condition causing the build to fail only sometimes? That's always a gotcha with testing async stuff.

**Comment by c-rack** [comment]
That's perfectly possible, yes. Don't have the time to investigate it further at the moment, too. But I am sure someone has the time and is able to fix it.

**Comment by daveyarwood** [comment]
Alright, sounds good to me 👍

**Pull request merged**
