### PR TITLE
Problem: ZAuthTest is flaky

### PR DESCRIPTION
**Pull request by fredoboulo**
Solution: add a timeout when sending a message, the authentication algorithm does not rely on the successful send
Bonus: removed deprecation annotations

### CODE REVIEW

**Comment by fbacchella** [comment]
I added @SuppressWarnings("deprecation") because of the use of org.junit.Assert.assertThat (see https://junit.org/junit4/javadoc/latest/org/junit/Assert.html#assertThat(java.lang.String,%20T,%20org.hamcrest.Matcher)).

Having so many deprecation warning everywhere creates confusion.

**Comment by fredoboulo** [comment]
The recommended way is to switch import to org.hamcrest.MatcherAssert.assertThat.

https://junit.org/junit4/javadoc/latest/org/junit/Assert.html#assertThat(T,%20org.hamcrest.Matcher).

Using assertThat can be discussed, I prefer that way for readability purposes.

**Comment by fbacchella** [comment]
My small tests bench return the following results:
```
org.zeromq.auth.ZAuthTest.testWhitelistDenied :
    cause:  {'test timed out after 5000 milliseconds': 1}
    type:   {'org.junit.runners.model.TestTimedOutException': 1}
org.zeromq.auth.ZAuthTest.testBlacklistDenied :
    cause:  {'test timed out after 5000 milliseconds': 3}
    type:   {'org.junit.runners.model.TestTimedOutException': 3}
"",min,max,median,average,std
"org.zeromq.auth.ZAuthTest.testPlainWithPasswordDenied",0.118,0.15,0.129,0.129660714286,0.00735399984876
"org.zeromq.auth.ZAuthTest.testWhitelistDenied",0.011,5.014,0.015,0.105,0.661935257948
"org.zeromq.auth.ZAuthTest.testNoReplies",0.005,0.016,0.0095,0.00976785714286,0.00207011966035
"org.zeromq.auth.ZAuthTest.testWhitelistAllowed",0.011,0.025,0.015,0.0158571428571,0.00332967486309
"org.zeromq.auth.ZAuthTest.testCurveSuccessful",0.133,0.171,0.153,0.153232142857,0.00964733692238
"org.zeromq.auth.ZAuthTest.testNull",0.008,0.02,0.012,0.0123571428571,0.00222348320232
"org.zeromq.auth.ZAuthTest.testBlacklistAllowed",0.009,0.024,0.012,0.0130178571429,0.00281888447686
"org.zeromq.auth.ZAuthTest.testPlainWithPassword",0.011,0.019,0.013,0.0131607142857,0.00158988752651
"org.zeromq.auth.ZAuthTest.testNullAllowed",0.007,0.017,0.0105,0.0110357142857,0.00206988859012
"org.zeromq.auth.ZAuthTest.testBlacklistDenied",0.009,5.016,0.0135,0.281375,1.12628389536
"org.zeromq.auth.ZAuthTest.testCurveAnyClient",0.05,0.06,0.053,0.0538392857143,0.0021694040139
"org.zeromq.auth.ZAuthTest.testNullWithNoDomain",1.008,1.017,1.011,1.01101785714,0.00164198346334
"org.zeromq.auth.ZAuthTest.testCurveFail",0.15,0.165,0.156,0.156214285714,0.00269731536979
```

After 60 runs.

**Comment by fredoboulo** [comment]
I ran 10k repetitions of testWhitelistDenied and testBlacklistDenied on my branch. No errors.
I'm using openjdk version "1.8.0_252" and java 11.0.2

**Comment by fbacchella** [comment]
Mine are runnning on a Centos 7.7 (kernel 3.10.0-1062.18.1.el7.x86_64) and java 11.0.6.

**Comment by fredoboulo** [comment]
I can try with JDK 11.0.6 on my linux machine this evening.
On an unrelated note, why are the CircleCI tests not running for the PR?

**Comment by fbacchella** [comment]
I have no idea, perhaps something in the settings ?

**Comment by fredoboulo** [comment]
Ran 100k repetitions using java 11.0.7, on ubuntu: no errors.

**Pull request merged**
