### PR TITLE
Fix #443 - Remove dependency on kalium for a pure Java version of NaCl

### LINKED ISSUE #443: Problem: Version 0.4.1 is not compatible with Android
Adding security inadvertently broke android suppose. Kalium (libsodium wrapper) doesn't support android.

### PR DESCRIPTION
**Pull request by trevorbernard**

### CODE REVIEW

**Comment by daveyarwood** [comment]
I don't know much about Kalium/libsodium/JNaCl, but this looks like a straightforward replacement 👍

**Comment by trevorbernard** [comment]
The problem was you'd need to have libsodium installed on your computer/device and it broke jeromq on Android. Can you merge please?

**Comment by trevorbernard** [comment]
@daveyarwood: ^

**Comment by daveyarwood** [comment]
Yep, makes sense to me. Merging.

**Pull request merged**
