### PR TITLE
Rename setRouterHandlover() to setRouterHandover().

### PR DESCRIPTION
**Pull request by garydgregory**
https://github.com/zeromq/jeromq/issues/294

### CODE REVIEW

**Comment by miniway** [comment]
Thanks for the change, but I think it breaks some style checks. The project strictly adheres '4 spaces'

**Comment by garydgregory** [comment]
Fixed, please see https://github.com/zeromq/jeromq/compare/master...garydgregory:setRouterHandover

**Comment by miniway** [comment]
good, could you fix the typos in the arguments also?

**Comment by garydgregory** [comment]
Done.

**Pull request merged**
