### PR TITLE
Fault injection test demonstrating infinite loop in iopoller thread

### PR DESCRIPTION
**Pull request by ferozed**
We are hitting the nasty jeromq issue where the IOPoller thread consumes 100% cpu ( [Issue#506](https://github.com/zeromq/jeromq/issues/506). Somewhere there is mentioned a link to JDK issue ( purportedly fixed in jdk7 ) that mentions it might be due to a server closing a socket and sending a reset.

So I thought I would repro this. I wrote a simple ZMTP3 server that accepts requests from a client. When it gets the GREETING frame, the socket is closed. After that the `socket.send()` call hangs indefinitely. On attaching a debugger I notice that the Poller thread is spinning infinitely ( however, it does not consume 100% cpu ).

While this does not repro our bug, I still thought I would send this your way for investigation. It is also possible that I am not doing something correctly that causes the `send()` call to hang, even though the server socket is closed.

### CODE REVIEW

**Comment by ferozed** [comment]
Also, when I build master on my machine, two tests are failing.


```Failed tests:   testZLoopWithUDP(org.zeromq.TestZLoop): (..)
  testPollUdp(zmq.PollTest): (..)
Tests in error: 
  testPollTcp(zmq.PollTest)
```

Also, this bug doesnt repro with the latest master branch for some reason... but the ZMTP3 server I wrote could still be used for further fault injection testing.

**Comment by daveyarwood** [comment]
Looks like there is a checkstyle violation on this branch:

```
src/test/java/zmq/faultinjection/ZMTP3Server.java:[13,8] (imports) UnusedImports: Unused import - java.nio.channels.ClosedSelectorException.
```

It would also be good to update this branch against current master, and see whether this test passes at this point.

**Comment by ferozed** [comment]
hi! @daveyarwood  I have updated the pull request. Watching the build to see if it will pass....

**Comment by daveyarwood** [comment]
Hmm, it looks like a ClosedChannelException is happening and it's hanging when the ZMTP3 server attempts to exit:

```
DEBUG stop()
java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:257)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:300)
	at sun.nio.ch.SocketAdaptor$SocketInputStream.read(SocketAdaptor.java:192)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at java.io.DataInputStream.read(DataInputStream.java:149)
	at zmq.faultinjection.ZMTP3Server$RequestHandler.run(ZMTP3Server.java:272)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
DEBUG **** ZMTP3 TEST SERVER EXITING *****
```

**Comment by daveyarwood** [comment]
I'm closing this because it's over a year old and the build is failing. I'd be happy to pick it back up at some point.

**Pull request closed without merging**
