### PR TITLE
Change license from LGPL to MPLv2

### LINKED ISSUE #326: What is the status of the MPL license changes to this project?
The MPL statement at http://zeromq.org/area:licensing has been there for a while but it is hard to tell what projects it will apply to.

Is there any work in progress on moving this project to MPL?

### PR DESCRIPTION
**Pull request by daveyarwood**
Closes #326 and #327.

### CODE REVIEW

**Comment by c-rack** [comment]
Thanks a lot!

**Comment by c-rack** [comment]
By the way, the README still refers to the GPL.

**Comment by daveyarwood** [comment]
Good catch -- I'll fix that on master.

**Comment by trevorbernard** [comment]
Also, pom.xml has lgpl as it's license.

**Comment by daveyarwood** [comment]
Another good catch -- fixing...

**Comment by daveyarwood** [comment]
@trevorbernard It looks like there are numerous references to the LGPL as header comments in most (if not all?) of the source files. Example: https://github.com/zeromq/jeromq/blob/master/src/main/java/org/zeromq/ZThread.java#L1-L18

Should we remove these references to the license in the source files? Seems archaic in my opinion.

**Comment by lbustelo** [comment]
@c-rack @trevorbernard @daveyarwood Great work!. This will open the doors for many more Apache.org projects using 0MQ.

**Pull request merged**
